### ISSUE TITLE
Açık kaynak nerde

### ISSUE THREAD

**Issue by bruhboy345** [LetteMC/LetteClient#1]
ee hani nerde

**Comment by TheHusyin** [comment]
Açık kaynak değil sadece emeği geçenler var repoda

**Comment by bruhboy345** [comment]
github böyle gereksiz şeyler için kullanılacak bişey değil

**Comment by TheHusyin** [comment]
> github böyle gereksiz şeyler için kullanılacak bişey değil

client'ı geliştirmeyi bıraktım zaten yakında kaynak kodunu paylaşıcam
